-- Generated by scripts/generate.js — do not edit by hand
---@class Private
local Private = select(2, ...)

---@class RosterEntry
---@field nickname string
---@field battletag? string

---@type RosterEntry[]
local Roster = {
    { nickname = "Annoyance", battletag = "puma#1523" },
    { nickname = "Apex", battletag = "apexmachine#1449" },
    { nickname = "Apollo", battletag = "pwnstar#11783" },
    { nickname = "Bestman", battletag = "bestman#1653" },
    { nickname = "Bubble", battletag = "hm3boost#1688" },
    { nickname = "Dez", battletag = "itsneahvil#1266" },
    { nickname = "Drcuddles", battletag = "drcuddlesphd#1611" },
    { nickname = "Eeld", battletag = "eeld#1234" },
    { nickname = "Errmac", battletag = "jaybirrd#11458" },
    { nickname = "Frosty", battletag = "psykiatrick#1489" },
    { nickname = "Gold", battletag = "h8shot#1402" },
    { nickname = "Hun", battletag = "hundiddy#1280" },
    { nickname = "Jerk", battletag = "mordrag#11554" },
    { nickname = "Kami", battletag = "klaus#12266" },
    { nickname = "Lancr", battletag = "phaszr#1199" },
    { nickname = "Mosaik", battletag = "kiazom#1222" },
    { nickname = "Nmu", battletag = "mazed#11112" },
    { nickname = "Peer", battletag = "notlad#11770" },
    { nickname = "Rocky", battletag = "bonestorm#11570" },
    { nickname = "Sad", battletag = "ophidian#1948" },
    { nickname = "Sicarius", battletag = "acheronfate#1797" },
    { nickname = "Sluff", battletag = "sluff#11368" },
    { nickname = "Squish", battletag = "squeethetree#1185" },
    { nickname = "Tenillee", battletag = "tenille#1412" },
    { nickname = "Waffle", battletag = "waffletwo#1858" },
    { nickname = "Xhul", battletag = "xuedo#1579" },
}

---@type table<string, boolean>
Private.RosterNicknames = {}
for _, entry in ipairs(Roster) do
    Private.RosterNicknames[entry.nickname] = true
end

---@type table<string, string>
Private.BattleTagToNickname = {}
for _, entry in ipairs(Roster) do
    if entry.battletag then
        Private.BattleTagToNickname[entry.battletag] = entry.nickname
    end
end
