describe("ForceAddonSettings", function()
    after_each(Restore)

    it("is a no-op when NSRT is not present", function()
        Replace("NSRT", nil)
        Private.EnforceNSRT()
        assert.is_falsy(_G.NSRT)
    end)

    it("sets every ready-check sub-setting", function()
        Replace("NSRT", {})
        Private.EnforceNSRT()
        assert.is_true(NSRT.ReadyCheckSettings.RepairCheck)
        assert.is_true(NSRT.ReadyCheckSettings.GemCheck)
        assert.is_true(NSRT.ReadyCheckSettings.EnchantCheck)
        assert.is_true(NSRT.ReadyCheckSettings.RaidBuffCheck)
        assert.is_true(NSRT.ReadyCheckSettings.CraftedCheck)
        assert.is_true(NSRT.ReadyCheckSettings.MissingItemCheck)
        assert.is_true(NSRT.ReadyCheckSettings.SoulstoneCheck)
        assert.is_true(NSRT.ReadyCheckSettings.ItemLevelCheck)
    end)

    it("enables each tracked encounter alert", function()
        Replace("NSRT", {})
        Private.EnforceNSRT()
        assert.is_true(NSRT.EncounterAlerts[3176].enabled)
        assert.is_true(NSRT.EncounterAlerts[3183].enabled)
        assert.is_true(NSRT.EncounterAlerts[3306].enabled)
    end)

    it("forces the QoL defaults", function()
        Replace("NSRT", {})
        Private.EnforceNSRT()
        assert.is_true(NSRT.QoL.SoulwellDropped)
        assert.is_true(NSRT.QoL.AutoInvite)
        assert.is_true(NSRT.QoL.ResetBossDisplay)
        assert.is_true(NSRT.QoL.LootBossReminder)
    end)

    it("enables reminder settings", function()
        Replace("NSRT", {})
        Private.EnforceNSRT()
        assert.is_true(NSRT.ReminderSettings.enabled)
    end)

    it("forces UseTLReminders off", function()
        Replace("NSRT", { ReminderSettings = { UseTLReminders = true } })
        Replace(Blizz, "BNGetInfo", function()
            return nil, nil
        end)
        Private.EnforceNSRT()
        assert.is_false(NSRT.ReminderSettings.UseTLReminders)
    end)

    it("preserves unknown keys on nested tables", function()
        Replace("NSRT", { ReadyCheckSettings = { RepairCheck = true, CustomSetting = "keep" } })
        Private.EnforceNSRT()
        assert.are.equal("keep", NSRT.ReadyCheckSettings.CustomSetting)
        assert.is_true(NSRT.ReadyCheckSettings.RepairCheck)
    end)

    it("enables GlobalNickNames", function()
        Replace("NSRT", {})
        Replace(Blizz, "BNGetInfo", function()
            return nil, nil
        end)
        Private.EnforceNSRT()
        assert.is_true(NSRT.Settings["GlobalNickNames"])
    end)

    it("sets MyNickName from the battle tag", function()
        Replace("NSRT", {})
        Replace(Blizz, "BNGetInfo", function()
            return nil, "waffletwo#1858"
        end)
        Private.EnforceNSRT()
        assert.are.equal("Waffle", NSRT.Settings["MyNickName"])
    end)

    it("matches battle tags case-insensitively", function()
        Replace("NSRT", {})
        Replace(Blizz, "BNGetInfo", function()
            return nil, "WaffleTwo#1858"
        end)
        Private.EnforceNSRT()
        assert.are.equal("Waffle", NSRT.Settings["MyNickName"])
    end)

    it("leaves MyNickName alone for unknown battle tags", function()
        Replace("NSRT", { Settings = { MyNickName = "Original" } })
        Replace(Blizz, "BNGetInfo", function()
            return nil, "unknown#0000"
        end)
        Private.EnforceNSRT()
        assert.are.equal("Original", NSRT.Settings["MyNickName"])
    end)

    it("enables SpellTTS", function()
        Replace("NSRT", {})
        Replace(Blizz, "BNGetInfo", function()
            return nil, nil
        end)
        Private.EnforceNSRT()
        assert.is_true(NSRT.ReminderSettings.SpellTTS)
    end)

    it("enables TextTTS", function()
        Replace("NSRT", {})
        Replace(Blizz, "BNGetInfo", function()
            return nil, nil
        end)
        Private.EnforceNSRT()
        assert.is_true(NSRT.ReminderSettings.TextTTS)
    end)
end)
