require("dotenv").config();

const fs = require("fs");
const path = require("path");
const { generateTTS } = require("./generate-tts");

const projectRoot = path.join(__dirname, "..");
const rosterPath = path.join(__dirname, "roster.json");
const privateAuraSoundsPath = path.join(__dirname, "private-aura-sounds.json");
const reminderSoundsPath = path.join(__dirname, "reminder-sounds.json");
const rosterOutputPath = path.join(projectRoot, "Core", "Roster.lua");
const auraSoundsOutputPath = path.join(
  projectRoot,
  "Features",
  "PrivateAuraSoundsData.lua"
);
const reminderSoundsOutputPath = path.join(
  projectRoot,
  "Features",
  "ReminderSoundsData.lua"
);
const ttsBaseDir = path.join(projectRoot, "Media", "TTS");
const reminderBaseDir = path.join(projectRoot, "Media", "Reminders");

function phraseToPascalCase(phrase) {
  return phrase
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("")
    .replace(/[^a-zA-Z0-9]/g, "");
}

function luaString(s) {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// ---------------------------------------------------------------------------
// Parse inputs
// ---------------------------------------------------------------------------

const rosterRaw = JSON.parse(fs.readFileSync(rosterPath, "utf-8"));
const nicknames = Object.keys(rosterRaw).sort();

const roster = {};
for (const nickname of nicknames) {
  const val = rosterRaw[nickname];
  if (typeof val === "string") {
    roster[nickname] = { battletag: val, tts: nickname };
  } else {
    roster[nickname] = { battletag: val.battletag, tts: val.tts || nickname };
  }
}

const auraSections = JSON.parse(
  fs.readFileSync(privateAuraSoundsPath, "utf-8")
);

const reminderSections = JSON.parse(
  fs.readFileSync(reminderSoundsPath, "utf-8")
);

// ---------------------------------------------------------------------------
// 1. Generate Roster Lua
// ---------------------------------------------------------------------------

const luaEntries = nicknames
  .map((nickname) => {
    return `    { nickname = "${nickname}", battletag = "${roster[nickname].battletag}" },`;
  })
  .join("\n");

const rosterLua = `-- Generated by scripts/generate.js — do not edit by hand
---@class Private
local Private = select(2, ...)

---@class RosterEntry
---@field nickname string
---@field battletag? string

---@type RosterEntry[]
local Roster = {
${luaEntries}
}

---@type table<string, boolean>
Private.RosterNicknames = {}
for _, entry in ipairs(Roster) do
    Private.RosterNicknames[entry.nickname] = true
end

---@type table<string, string>
Private.BattleTagToNickname = {}
for _, entry in ipairs(Roster) do
    if entry.battletag then
        Private.BattleTagToNickname[entry.battletag] = entry.nickname
    end
end
`;

fs.writeFileSync(rosterOutputPath, rosterLua);
console.log(
  `Generated ${path.relative(projectRoot, rosterOutputPath)} (${nicknames.length} members)`
);

// ---------------------------------------------------------------------------
// 2. Generate PrivateAuraSoundsData Lua
// ---------------------------------------------------------------------------

let currentRaid = null;
const lines = [];

lines.push("-- Generated by scripts/generate.js — do not edit by hand");
lines.push("---@class Private");
lines.push("local Private = select(2, ...)");
lines.push("");
lines.push("---@type PrivateAuraBossSection[]");
lines.push("Private.PrivateAuraSections = {");

for (const section of auraSections) {
  if (section.raid !== currentRaid) {
    currentRaid = section.raid;
    lines.push(`    -- ${currentRaid}`);
  }
  lines.push("    {");
  lines.push(`        boss = ${luaString(section.boss)},`);
  if (section.bigwigsModule) {
    lines.push(
      `        bigwigsModule = ${luaString(section.bigwigsModule)},`
    );
  }
  lines.push("        spells = {");

  for (const spell of section.spells) {
    const perUnit = spell.perUnit || false;
    const soundFile = spell.soundFile || phraseToPascalCase(spell.phrase);
    const ids = spell.spellIDs.join(", ");

    lines.push(`            -- ${spell.comment}`);
    if (perUnit) {
      lines.push(
        `            { spellIDs = {${ids}}, soundDir = ${luaString(spell.soundDir)}, perUnit = true },`
      );
    } else {
      lines.push(
        `            { spellIDs = {${ids}}, soundFile = ${luaString(soundFile)}, perUnit = false },`
      );
    }
  }

  lines.push("        },");
  lines.push("    },");
}

lines.push("}");
lines.push("");

fs.writeFileSync(auraSoundsOutputPath, lines.join("\n"));
console.log(
  `Generated ${path.relative(projectRoot, auraSoundsOutputPath)} (${auraSections.length} bosses, ${auraSections.reduce((n, s) => n + s.spells.length, 0)} spells)`
);

// ---------------------------------------------------------------------------
// 3. Generate ReminderSoundsData Lua
// ---------------------------------------------------------------------------

currentRaid = null;
const reminderLines = [];

reminderLines.push("-- Generated by scripts/generate.js — do not edit by hand");
reminderLines.push("---@class Private");
reminderLines.push("local Private = select(2, ...)");
reminderLines.push("");
reminderLines.push("---@type ReminderSoundBossSection[]");
reminderLines.push("Private.ReminderSoundSections = {");

for (const section of reminderSections) {
  if (section.raid !== currentRaid) {
    currentRaid = section.raid;
    reminderLines.push(`    -- ${currentRaid}`);
  }
  reminderLines.push("    {");
  reminderLines.push(`        boss = ${luaString(section.boss)},`);
  if (section.encounterID) {
    reminderLines.push(`        encounterID = ${section.encounterID},`);
  }
  reminderLines.push("        reminders = {");

  for (const reminder of section.reminders) {
    const soundFile = reminder.soundFile || phraseToPascalCase(reminder.phrase);
    reminderLines.push(
      `            { text = ${luaString(reminder.text)}, soundFile = ${luaString(soundFile)} },`
    );
  }

  reminderLines.push("        },");
  reminderLines.push("    },");
}

reminderLines.push("}");
reminderLines.push("");

fs.writeFileSync(reminderSoundsOutputPath, reminderLines.join("\n"));
const reminderCount = reminderSections.reduce(
  (n, s) => n + s.reminders.length,
  0
);
console.log(
  `Generated ${path.relative(projectRoot, reminderSoundsOutputPath)} (${reminderSections.length} bosses, ${reminderCount} reminders)`
);

// ---------------------------------------------------------------------------
// 4. Generate TTS audio
// ---------------------------------------------------------------------------

const perUnitSoundSets = [];
const oneOffSounds = {};

for (const section of auraSections) {
  for (const spell of section.spells) {
    if (spell.perUnit) {
      if (!perUnitSoundSets.some((s) => s.dir === spell.soundDir)) {
        perUnitSoundSets.push({
          dir: spell.soundDir,
          phrase: (name) => spell.phrase.replace("{name}", name),
        });
      }
    } else {
      const soundFile = spell.soundFile || phraseToPascalCase(spell.phrase);
      if (!oneOffSounds[soundFile]) {
        // Capitalize first letter of each word for TTS
        oneOffSounds[soundFile] = spell.phrase;
      }
    }
  }
}

const reminderSounds = {};
for (const section of reminderSections) {
  for (const reminder of section.reminders) {
    const soundFile = reminder.soundFile || phraseToPascalCase(reminder.phrase);
    if (!reminderSounds[soundFile]) {
      reminderSounds[soundFile] = reminder.phrase;
    }
  }
}

async function generateAllTTS() {
  for (const soundSet of perUnitSoundSets) {
    const outputDir = path.join(ttsBaseDir, soundSet.dir);
    const entries = {};
    for (const nickname of nicknames) {
      entries[nickname] = soundSet.phrase(roster[nickname].tts);
    }
    entries["Unknown"] = soundSet.phrase("Unknown");
    console.log(`\nTTS sound set: ${soundSet.dir}`);
    await generateTTS(outputDir, entries);
  }

  if (Object.keys(oneOffSounds).length > 0) {
    console.log("\nTTS one-off sounds:");
    await generateTTS(ttsBaseDir, oneOffSounds);
  }

  if (Object.keys(reminderSounds).length > 0) {
    console.log("\nTTS reminder sounds:");
    await generateTTS(reminderBaseDir, reminderSounds);
  }
}

generateAllTTS().catch((err) => {
  console.error("TTS generation failed:", err.message);
  process.exit(1);
});
