require("dotenv").config();

const fs = require("fs");
const path = require("path");
const { generateTTS } = require("./generate-tts");

const projectRoot = path.join(__dirname, "..");
const rosterPath = path.join(__dirname, "roster.json");
const outputPath = path.join(projectRoot, "Core", "Roster.lua");
const ttsBaseDir = path.join(projectRoot, "Media", "TTS");

// Per-unit TTS sound sets: generates one file per roster member in a subdirectory.
// Add new entries here when new per-unit private aura spells are added.
const perUnitSoundSets = [
  {
    dir: "DreadBreath",
    phrase: (name) => `Breath on ${name}`,
  },
];

// One-off TTS sounds: generates a single file in Media/TTS/.
// Add new entries here for non-per-unit private aura sounds.
const oneOffSounds = {
  ArrowOnYou: "Arrow on You",
};

// --- Parse roster ---

const rosterRaw = JSON.parse(fs.readFileSync(rosterPath, "utf-8"));
const nicknames = Object.keys(rosterRaw).sort();

// Normalize entries: string value = battletag only, object = { battletag, tts? }
const roster = {};
for (const nickname of nicknames) {
  const val = rosterRaw[nickname];
  if (typeof val === "string") {
    roster[nickname] = { battletag: val, tts: nickname };
  } else {
    roster[nickname] = { battletag: val.battletag, tts: val.tts || nickname };
  }
}

// --- Lua generation ---

const luaEntries = nicknames
  .map((nickname) => {
    return `    { nickname = "${nickname}", battletag = "${roster[nickname].battletag}" },`;
  })
  .join("\n");

const luaContent = `-- Generated by scripts/generate-roster.js — do not edit by hand
---@class Private
local Private = select(2, ...)

---@class RosterEntry
---@field nickname string
---@field battletag? string

---@type RosterEntry[]
local Roster = {
${luaEntries}
}

---@type table<string, boolean>
Private.RosterNicknames = {}
for _, entry in ipairs(Roster) do
    Private.RosterNicknames[entry.nickname] = true
end

---@type table<string, string>
Private.BattleTagToNickname = {}
for _, entry in ipairs(Roster) do
    if entry.battletag then
        Private.BattleTagToNickname[entry.battletag] = entry.nickname
    end
end
`;

fs.writeFileSync(outputPath, luaContent);
console.log(
  `Generated ${path.relative(projectRoot, outputPath)} (${nicknames.length} members)`
);

// --- TTS generation ---

async function generateAllTTS() {
  for (const soundSet of perUnitSoundSets) {
    const outputDir = path.join(ttsBaseDir, soundSet.dir);
    const entries = {};
    for (const nickname of nicknames) {
      entries[nickname] = soundSet.phrase(roster[nickname].tts);
    }
    entries["Unknown"] = soundSet.phrase("Unknown");
    console.log(`\nTTS sound set: ${soundSet.dir}`);
    await generateTTS(outputDir, entries);
  }

  if (Object.keys(oneOffSounds).length > 0) {
    console.log("\nTTS one-off sounds:");
    await generateTTS(ttsBaseDir, oneOffSounds);
  }
}

generateAllTTS().catch((err) => {
  console.error("TTS generation failed:", err.message);
  process.exit(1);
});
