-- Generated by scripts/generate.js — do not edit by hand
---@class Private
local Private = select(2, ...)

---@type PrivateAuraBossSection[]
Private.PrivateAuraSections = {
    -- The Voidspire
    {
        boss = "Imperator Averzian",
        bigwigsModule = "BigWigs_Bosses_Imperator Averzian",
        spells = {
            -- Void Marked
            { spellIDs = {1280023}, soundFile = "Shield", perUnit = false },
            -- Weakened (Voidspawn fixate)
            { spellIDs = {1283069}, soundFile = "Fixate", perUnit = false },
        },
    },
    {
        boss = "Vorasius",
        bigwigsModule = "BigWigs_Bosses_Vorasius",
        spells = {
            -- Fixate
            { spellIDs = {1254113}, soundFile = "Fixate", perUnit = false },
        },
    },
    {
        boss = "Fallen-King Salhadaar",
        bigwigsModule = "BigWigs_Bosses_Fallen-King Salhadaar",
        spells = {
            -- Shattering Twilight
            { spellIDs = {1268992, 1253024}, soundFile = "Spread", perUnit = false },
            -- Despotic Command
            { spellIDs = {1248697}, soundFile = "DropPool", perUnit = false },
        },
    },
    {
        boss = "Vaelgor & Ezzorak",
        bigwigsModule = "BigWigs_Bosses_Vaelgor & Ezzorak",
        spells = {
            -- Dread Breath
            { spellIDs = {1255612}, soundDir = "DreadBreath", perUnit = true },
            -- Shadowmark
            { spellIDs = {1270497}, soundFile = "Spread", perUnit = false },
        },
    },
    {
        boss = "Lightblinded Vanguard",
        bigwigsModule = "BigWigs_Bosses_Lightblinded Vanguard",
        spells = {
            -- Avenger's Shield
            { spellIDs = {1246487}, soundFile = "Spread", perUnit = false },
        },
    },
    {
        boss = "Crown of the Cosmos",
        bigwigsModule = "BigWigs_Bosses_Crown of the Cosmos",
        spells = {
            -- Silverstrike Arrow
            { spellIDs = {1233602}, soundFile = "ArrowOnYou", perUnit = false },
            -- Void Expulsion
            { spellIDs = {1283236}, soundFile = "DropPool", perUnit = false },
            -- Grasp of Emptiness
            { spellIDs = {1260027, 1232470}, soundFile = "Obelisk", perUnit = false },
            -- Ranger Captain's Mark
            { spellIDs = {1259861, 1237623}, soundFile = "ArrowOnYou", perUnit = false },
            -- Aspect of the End
            { spellIDs = {1239111}, soundFile = "Tether", perUnit = false },
        },
    },
    -- The Dreamrift
    {
        boss = "Chimaerus the Undreamt God",
        bigwigsModule = "BigWigs_Bosses_Chimaerus the Undreamt God",
        spells = {
            -- Rift Madness
            { spellIDs = {1264756}, soundFile = "Swap", perUnit = false },
            -- Consuming Miasma
            { spellIDs = {1257087}, soundFile = "Clear", perUnit = false },
        },
    },
    {
        boss = "Midnight Falls",
        bigwigsModule = "BigWigs_Bosses_Midnight Falls",
        spells = {
            -- Starsplinter
            { spellIDs = {1279512, 1285510}, soundFile = "Starsplinter", perUnit = false },
            -- Grim Symphony (Blue)
            { spellIDs = {1284984}, soundFile = "Blue", perUnit = false },
            -- Grim Symphony (Red)
            { spellIDs = {1286294}, soundFile = "Red", perUnit = false },
        },
    },
    -- Sporefall
    {
        boss = "Rotmire",
        bigwigsModule = "BigWigs_Bosses_Rotmire",
        spells = {
            -- Shroomling Fixate
            { spellIDs = {1221639}, soundFile = "GoToBoss", perUnit = false },
            -- Fungling Fixate
            { spellIDs = {1299508}, soundFile = "GoToRanged", perUnit = false },
        },
    },
}
