-- Generated by scripts/generate.js — do not edit by hand
---@class Private
local Private = select(2, ...)

---@type ReminderSoundBossSection[]
Private.ReminderSoundSections = {
    -- undefined
    {
        boss = "General",
        reminders = {
            { text = "Soulstone", soundFile = "Soulstone" },
            { text = "Source of Magic", soundFile = "SourceOfMagic" },
            { text = "Rebuff Battle Shout", soundFile = "RebuffBattleShout" },
            { text = "Rebuff Power Word: Fortitude", soundFile = "RebuffPowerWordFortitude" },
            { text = "Rebuff Skyfury", soundFile = "RebuffSkyfury" },
            { text = "Rebuff Arcane Intellect", soundFile = "RebuffArcaneIntellect" },
            { text = "Rebuff Mark of the Wild", soundFile = "RebuffMarkOfTheWild" },
            { text = "Rebuff Blessing of the Bronze", soundFile = "RebuffBlessingOfTheBronze" },
        },
    },
    -- The Voidspire
    {
        boss = "Imperator Averzian",
        encounterID = 3176,
        reminders = {
            { text = "Soak", soundFile = "Soak" },
        },
    },
    {
        boss = "Vorasius",
        encounterID = 3177,
        reminders = {
            { text = "Knock", soundFile = "Knock" },
            { text = "Breath", soundFile = "Breath" },
        },
    },
    {
        boss = "Fallen-King Salhadaar",
        encounterID = 3179,
        reminders = {
            { text = "Beams", soundFile = "Beams" },
            { text = "Orbs", soundFile = "Orbs" },
            { text = "CC Adds", soundFile = "CcAdds" },
        },
    },
    {
        boss = "Vaelgor & Ezzorak",
        encounterID = 3178,
        reminders = {
            { text = "Spread", soundFile = "Spread" },
            { text = "Tether", soundFile = "Tether" },
            { text = "Breath", soundFile = "Breath" },
            { text = "Soak", soundFile = "Soak" },
            { text = "Don't soak", soundFile = "DontSoak" },
            { text = "Gloom 1 Triangle", soundFile = "Gloom1Triangle" },
            { text = "Gloom 2 Star", soundFile = "Gloom2Star" },
            { text = "Gloom 1 Diamond", soundFile = "Gloom1Diamond" },
            { text = "Gloom 2 Circle", soundFile = "Gloom2Circle" },
            { text = "Breath Square", soundFile = "BreathSquare" },
            { text = "Breath Circle", soundFile = "BreathCircle" },
            { text = "Mass Grip", soundFile = "MassGrip" },
            { text = "Chains", soundFile = "Chains" },
        },
    },
    {
        boss = "Lightblinded Vanguard",
        encounterID = 3180,
        reminders = {
            { text = "Sacred Toll", soundFile = "SacredToll" },
            { text = "Taunt", soundFile = "Taunt" },
            { text = "Go to Star", soundFile = "GoToStar" },
            { text = "Go to Orange", soundFile = "GoToOrange" },
            { text = "Go to Purple", soundFile = "GoToPurple" },
            { text = "Go to Green", soundFile = "GoToGreen" },
            { text = "Soak Star", soundFile = "SoakStar" },
            { text = "Soak Orange", soundFile = "SoakOrange" },
            { text = "Soak Purple", soundFile = "SoakPurple" },
            { text = "Soak Green", soundFile = "SoakGreen" },
            { text = "Move General Out", soundFile = "MoveGeneralOut" },
            { text = "Move Commander Out", soundFile = "MoveCommanderOut" },
            { text = "Move Chaplain Out", soundFile = "MoveChaplainOut" },
            { text = "Group Soak", soundFile = "GroupSoak" },
            { text = "Bait Charge", soundFile = "BaitCharge" },
        },
    },
    {
        boss = "Crown of the Cosmos",
        encounterID = 3181,
        reminders = {
            { text = "Stop Cast", soundFile = "StopCast" },
            { text = "Arrows", soundFile = "Arrows" },
            { text = "Explosion", soundFile = "Explosion" },
            { text = "Tether", soundFile = "Tether" },
            { text = "Bait", soundFile = "Bait" },
        },
    },
    -- The Dreamrift
    {
        boss = "Chimaerus the Undreamt God",
        encounterID = 3306,
        reminders = {
            { text = "Soak", soundFile = "Soak" },
            { text = "Don't soak", soundFile = "DontSoak" },
            { text = "Debuffs", soundFile = "Debuffs" },
        },
    },
    {
        boss = "Beloren",
        encounterID = 3182,
        reminders = {
            { text = "Gateway", soundFile = "Gateway" },
        },
    },
    {
        boss = "Midnight Falls",
        encounterID = 3183,
        reminders = {
            { text = "Memory Game", soundFile = "MemoryGame" },
            { text = "Glaives", soundFile = "Glaives" },
            { text = "Interrupts", soundFile = "Interrupts" },
            { text = "Beams", soundFile = "Beams" },
            { text = "Orbs", soundFile = "Orbs" },
            { text = "Crystal", soundFile = "Crystal" },
            { text = "Soaks", soundFile = "Soaks" },
            { text = "Blazes", soundFile = "Blazes" },
            { text = "Move", soundFile = "Move" },
            { text = "Soak Skull", soundFile = "SoakSkull" },
            { text = "Soak X", soundFile = "SoakX" },
        },
    },
}
