name: release

on:
  push:
    tags:
      - '**'

env:
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@v2
